/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import org.junit.Test;
import static org.junit.Assert.*;

import javax.swing.plaf.TreeUI;

import org.junit.*;
import blackjack.model.*;

public class AppTest {

    User user;
    Dealer dealer;
    Table table;
    
    @Before
    public void setUp() {
        user = new User();
        dealer = new Dealer();
        table = new Table(dealer, user);
    }

    @After
    public void tearDown(){
        user = null;
        dealer = null;
        table = null;
    }

    @Test
    public void userTestHandSize(){
        user.pullRandomCard();
        user.pullRandomCard();

        assertEquals("Should have 2 cards", 2, user.getTotalCards());
    }

    @Test
    public void userTestBust(){
        /*Pulling 10 cards to guarantee bust. */
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();
        user.pullRandomCard();

        assertEquals("User stands after busting", true, user.isStanding());
    }

    @Test 
    public void userLoanTest(){
        user.playerLoaned(100);

        assertEquals("Debt total", 100, user.getDebt());
        assertEquals("balance total" , 5100, user.getBalance());
    }
}
