/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import blackjack.view.BlackJackGui;
import blackjack.view.LoanShark;

public class App {

    public static void main(String[] args) {
        BlackJackGui blackJackGui = new BlackJackGui();
        LoanShark loanSharkGUI = new LoanShark();
    }
}
