/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import blackjack.view.BlackJackGui;

public class App {

    public static void main(String[] args) {
        BlackJackGui blackJackGui = new BlackJackGui();
    }
}
