/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import blackjack.model.*;
import blackjack.controller.*;

public class App {

    public static void main(String[] args) {

        User player = new User(); // model

        Controller controller = new Controller(player); //controller
    }
}
